### ISSUE TITLE
Fatal error: EMFILE in Windows.

### ISSUE THREAD

**Issue by gamedevhelper** [MorrisLLC/grunt-war#14]
I am unable to create .war files in Windows.
Here is my output. 
Running "war:target" (war) task
Fatal error: EMFILE, open 'X:\src\webdev\testwar\node_modules\grunt-contrib-connect\node_modules\connect\node_modules\morgan\HISTORY.md' 

(The file is https://github.com/expressjs/morgan/blob/master/HISTORY.md)
(The project is generated using https://github.com/yeoman/generator-angular)

**Comment by wibobm** [comment]
I'll check this out later today.  Thank you.

**Comment by wibobm** [comment]
I'm pretty sure this is fixed grunt-war 0.4.6

**Comment by wibobm** [comment]
This is fixed.
