### ISSUE TITLE
v0.4.7 copies files into WAR as folders

### ISSUE THREAD

**Issue by rbalmf** [MorrisLLC/grunt-war#15]
Since upgrading to 0.4.7 grunt-war has been producing war files full of folders, where files are expected.  e.g. "index.html" file in root of war has become empty folder "index.html", and so on.

The problem goes away if we roll back to 0.4.6.

From the gruntfile (unchanged, works with <= 0.4.6, fails as above = 0.4.7):

		war: {
			dist: {
				options: {
					war_dist_folder: 'dist',
					war_verbose: true,
					war_name: 'foo',
					webxml: function() {
						var fs = require('fs');
						return fs.readFileSync('resources/web.xml');
					}
				},
				files: [{
					expand: true,
					cwd: 'dist/web',
					src: ['**']
				}]
			}
		}

Thanks.

**Comment by wibobm** [comment]
I'm going to burn my fingers with a hot iron for this one.  I'll fix this here very soon - I'm glad 0.4.6 is working for you as a work around.

**Comment by rbalmf** [comment]
Thanks, force be with you!

**Comment by wibobm** [comment]
Can you give 0.4.8 a whirl real quick?  If it's all good -- I'll send you a Kringle from Racine, WI.  If not I might become a Sith Lord from the fear consuming me.

**Comment by rbalmf** [comment]
Sure, I'll spin it up now...

**Comment by rbalmf** [comment]
Works like a boss!  Awesome job wibobm, the Kringle's all yours!

**Comment by wibobm** [comment]
It's up to you!  I'll have an authentic Danish Kringle shipped directly from the bakery to you.. just follow me on Twitter @wibobm then you can DM me the ship to address.  You can then unfollow -- I'm really not  all that interesting on Twitter ;)

**Comment by wibobm** [comment]
Hey - if your happy can you close the issue?

**Comment by rbalmf** [comment]
LOL!  Well if you twist my arm!  :)   Yes please do close issue, thanks again for quick response!
