### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by ssc-hrep3** [MorrisLLC/grunt-war#16]
Is it possible to add a flag, that the index.html (the default file) is not cached? My index.html contains only very little code and mainly references to a javascript and a css files. Those files are revved with filerev, so the index.html would be the only file, which does not need to be cached.

**Comment by wibobm** [comment]
Just to be clear you want the ability to exclude the index.html from the war archive?

**Comment by ssc-hrep3** [comment]
No, I want the index.html to have a HTTP header cache-control: no-cache, must-revalidate.

**Comment by wibobm** [comment]
The container (Tomcat for example) that you are deploying the WAR should have features that allow you to set the cache-control and other headers for the resources being served in much the same way that .htaccess provides this functionality for Apache.  A WAR is really just a zip file of all your resources and is not technically running any code (unless you package some Java servlet code along side your browser web app in the same WAR).  Prior to HTML5 some success could be achieved by including meta tags inside individual files (index.html for example) like <meta http-equiv="Cache-control" content="no-cache"> and this may still work in HTML5 browsers but it is technically not supposed to be allowed in HTML5.  Now with HTML5 you have the tag <html manifest="manifest.appcache"> which gives you some control but likely not what you are looking to achieve.

**Comment by ssc-hrep3** [comment]
Thank you for this information! I found a Tomcat filter which handles this usecase.
