### ISSUE TITLE
How to exclude files from the WAR?

### ISSUE THREAD

**Issue by Giwayume** [MorrisLLC/grunt-war#18]
I see the documentation list the src

```
src: ['**']
```

However, I can't find any documentation on how to manipulate this. I just want to exclude a file extension.

**Comment by wibobm** [comment]
I'll write up an example for you in a short bit here today.  Thank you for the question.

**Comment by wibobm** [comment]
At the end of the src array add '!path-to-file-to-exclude.js'.  

So...

src: ['**', '!path-to-file-to-exclude.js']

**Comment by Giwayume** [comment]
And if I want to exclude every .js file, it's?

```
src: ['**', '!*.js']
```

**Comment by wibobm** [comment]
If you want them ALL excluded:

`src: ['**', '!**/*.js']`

**Comment by Giwayume** [comment]
That worked, thanks!
