### ISSUE TITLE
grunt-war not working at all

### ISSUE THREAD

**Issue by mgaouar** [MorrisLLC/grunt-war#19]
Hello,

I am trying to use grunt-war in my yeoman application and it's not working, I have my CPU running high and no errors are displayed on screen or anything like that.

Here is my task definition:

``` javascript
// Generate war file
    war: {
      target: {
        options: {
          war_verbose: true,
          war_dist_folder: '<%= yeoman.dist %>',
          war_name: 'dpaUi',
          webxml_welcome: 'index.html',
          webxml_display_name: 'Some description of the WAR'
        }
      },
      files: [
        {
          expand: true,
          cwd: '<%= yeoman.dist %>',
          src: ['**'],
          dst: '.'
        }
      ]
    }
```

I added the war step into default right after build and I tried it stand alone after doing a build. Nothing worked for me.

**Comment by wibobm** [comment]
I put together this tiny Gruntfile as a sample that should WAR up your assets and place the war inside your ‘yeoman.dist', folder.

Simply save it to a file called gruntfile-war.js in the same folder as your existing Gruntfile.js.  You should then be able to build a war with the following command from the command line:

% grunt --gruntfile gruntfile-war.js war

If no warnings or errors you should the have a war inside your  folder called grunt-magic.war!

Given this example you should be able to add a task in your Gruntfile.js that performs the same assembly.

— gruntfule-war.js.

```
module.exports = function ( grunt ) {
grunt.loadNpmTasks( 'grunt-war' );

var taskConfig = {
    war: {
        target: {
            options: {
                war_verbose: true,
                war_dist_folder: 'what_folder_to_place_war',     // <-- READ
                war_name: 'grunt-magic',           // .war will be appended if omitted
                webxml_welcome: 'index.html',
                webxml_display_name: 'Grunt Magic'
            },
            files: [
                {
                    expand: true,
                    cwd: 'what_folder_to_find_your_client_code_ready_for_packaging_up',   // <-- READ
                    src: ['**'],
                    dest: ''
                }
            ]
        }
    }
};

grunt.initConfig( taskConfig );
};
```

**Comment by wibobm** [comment]
My apologies for not responding right away.  Somehow this mail slipped passed my radar.

I respond to the issue on GitHub.  I’m pretty sure it boils down to using yeoman.dist as both the source and distribution folder.

**Comment by mgaouar** [comment]
Sorry for replying earlier about this, we changed our whole technology stack lol so we are not using war files at all. Thanks for your help and support!
